1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np
zp= np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [3]:
cov= np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [4]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [5]:
np.cov(zp, ks, ddof = 1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [6]:
np.cov(zp, ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [7]:
t = 2.262
l = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]
x = sum(l) / float(len(l))
print(x)

118.1


In [8]:
import statistics

d = statistics.variance(l, x)
print(d)

111.21111111111111


In [9]:
import math
n1 = x-t*math.sqrt(d)/math.sqrt(float(len(l)))
n2 = x+t*math.sqrt(d)/math.sqrt(float(len(l)))
print(n1)
print(n2)

110.55660776308164
125.64339223691834


3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

F(t) = 0.95/2
t = 1.96


In [10]:
n1 = 174.2-1.96*5/math.sqrt(27)
n2 = 174.2+1.96*5/math.sqrt(27)
print(n1)
print(n2)

164.7699456032361
183.63005439676388
