1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [3]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = 10
b1 = (n*np.sum(zp*ks) - np.sum(zp)*np.sum(ks))/(n*np.sum(zp**2) - np.sum(zp)**2)
b1

2.6205388824027653

In [4]:
b0 = np.mean(ks) - b1*np.mean(zp)
b0

444.17735732435955

In [5]:
x = zp.reshape(10,1)
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [6]:
y = ks.reshape(10,1)
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [7]:
X = np.hstack([np.ones((10,1)), x])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [8]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)), X.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [11]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [12]:
def mse_(B1, y = y, x = x, n = 10):
    return np.sum((B1*x - y)**2)

In [16]:

B1 = 0.1
n = 10


In [19]:
for i in range (300):
    B1 -=0.000001* (2/n) * np.sum((B1*x - y)*x)
    print ("B1 = {}".format(B1))

B1 = 1.6319792141937546
B1 = 1.7492963645092312
B1 = 1.8633810519186353
B1 = 1.9743223411189108
B1 = 2.082206842789593
B1 = 2.187118781208843
B1 = 2.2891400600064395
B1 = 2.38835032610507
B1 = 2.484827031899832
B1 = 2.5786454957244893
B1 = 2.6698789606516935
B1 = 2.7585986516730654
B1 = 2.844873831303787
B1 = 2.9287718536551073
B1 = 3.0103582170169774
B1 = 3.089696614991865
B1 = 3.166848986219671
B1 = 3.2418755627325635
B1 = 3.3148349169774805
B1 = 3.3857840075430166
B1 = 3.4547782236263824
B1 = 3.52187142827516
B1 = 3.587116000437609
B1 = 3.6505628758543516
B1 = 3.7122615868233613
B1 = 3.7722603008693
B1 = 3.8306058583473876
B1 = 3.8873438090111705
B1 = 3.942518447572724
B1 = 3.996172848283063
B1 = 4.04834889855975
B1 = 4.0990873316879535
B1 = 4.148427758620489
B1 = 4.196408698901667
B1 = 4.2430676107390894
B1 = 4.288440920246873
B1 = 4.332564049883127
B1 = 4.375471446103887
B1 = 4.417196606255097
B1 = 4.457772104723629
B1 = 4.497229618367758
B1 = 4.535599951246947
B1 = 4.572913058670